### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wang-yun** [aofeng/threadpool4j#1]
1. 用maven管理依赖
2. 将log4j 日志输出改成slf4j + logback
3. 把未开源的两个依赖改成使用开源包

**Comment by aofeng** [comment]
谢谢你的建议：
1、后续同时提供Ant和Maven两种打包方式。
2、log4j基本垄断了Java项目中的日志输出，性能出色，看不出改为slf4j+logback的价值，所以不修改。
3、哪两个依赖包未开源？请指出。

**Comment by aofeng** [comment]
日志输出已经由log4j改成slf4j，方便各项目集成不同的日志框架（如：log4j，logback等）
