### ISSUE TITLE
自定义线程名称

### ISSUE THREAD

**Issue by zghnzch** [aofeng/threadpool4j#10]
自定义线程名称 不是线程池名称

**Comment by aofeng** [comment]
请描述清楚你的需求和使用的场景。

目前线程池中线程的命名规则是：线程池名称+"="+数字编号。

**Comment by aofeng** [comment]
请描述清楚你的需求和使用的场景。

目前线程池中线程的命名规则是：线程池名称+"-"+数字编号。

**Comment by zghnzch** [comment]
这边有一个系统udp端口监听的线程（非定时任务）在系统启动的时候运行，但中间不知道什么问题总是自动结束掉，没有异常，因为这个线程是跟下面硬件相关的（物联网设备），我需要保持这个线程一直在运行的状态，所以做了udp端口监听线程的检测线程 发现udp线程异常结束之后就再次启动，之前是根据线程名称检测的，现在想使用线程池去调度，就不知道怎么去检测了

**Comment by aofeng** [comment]
> 这边有一个系统udp端口监听的线程（非定时任务）在系统启动的时候运行，但中间不知道什么问题总是自动结束掉，没有异常，因为这个线程是跟下面硬件相关的（物联网设备），我需要保持这个线程一直在运行的状态，所以做了udp端口监听线程的检测线程 发现udp线程异常结束之后就再次启动，之前是根据线程名称检测的，现在想使用线程池去调度，就不知道怎么去检测了

这个场景不适合用这种通用的线程池，通用的线程池会给其中每一个线程唯一的命名，方便区分。
监听UDP端口的线程，你可以用Thread自己写一个，给它取一个单独的名字。
