### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by booldplx** [aofeng/threadpool4j#13]
使用ant编译的jar包，在threadPoolManager.init()的时候报错NullPointerException: Attempt to invoke interface method 'org.w3c.dom.Element org.w3c.dom.Document.getDocumentElement()，还有请问一下，在Android项目中，配置文件应该放在哪里呢，谢谢

**Comment by aofeng** [comment]
报这个错，是找不到配置文件导致的。
Android项目是一个新的使用场景，没有测试过。我们都是在Java后端项目中使用。

欢迎Fork这个项目，做改进，使之兼容Android项目，然后Pull Request。
