### ISSUE TITLE
import cn.aofeng.common4j.ILifeCycle;

### ISSUE THREAD

**Issue by winnery2007** [aofeng/threadpool4j#14]
import cn.aofeng.common4j.ILifeCycle; 这个包好像没有啊，另外springboot项目怎么使用呢

**Comment by zhuangjianfen** [comment]
来信已收到，谢谢！

**Comment by winnery2007** [comment]
这个包依赖于作者的另外一个项目，需要自己下载，其实我是建议作者自己把这个组件加入进来，然后我启动项目的时候 还是会报错 Exception in thread "main" java.lang.IllegalArgumentException: thread pool default not exists

**Comment by zhuangjianfen** [comment]
来信已收到，谢谢！

**Comment by aofeng** [comment]
> 这个包依赖于作者的另外一个项目，需要自己下载，其实我是建议作者自己把这个组件加入进来，然后我启动项目的时候 还是会报错 Exception in thread "main" java.lang.IllegalArgumentException: thread pool default not exists

谢谢你的建议！在下一个版本中改进，后续打算上Maven仓库。

**Comment by aofeng** [comment]
已经发布到Maven中心仓库。

**Comment by zhuangjianfen** [comment]
来信已收到，谢谢！
