### ISSUE TITLE
当最大线程数超过队列大小时不能自定义处理策略

### ISSUE THREAD

**Issue by xiyoufang** [aofeng/threadpool4j#2]
建议内置部分策略例如：等待、丢弃、异常 等，并暴露接口。

**Comment by aofeng** [comment]
好建议！本周发布的下一个版本会包含这个特性。

**Comment by aofeng** [comment]
实现这个特性的主要思路：
1、定义接口并实现部分内置处理策略。
2、用户可以自定义处理策略。

**Comment by aofeng** [comment]
包含上述特性的3.0.0版本已经发布，请情可查看：https://github.com/aofeng/threadpool4j/releases/tag/v3.0.0
