### ISSUE TITLE
需求请教一个问题

### ISSUE THREAD

**Issue by rtwo1987** [aofeng/threadpool4j#3]
配置xml文件时，说明为：“在应用的CLASSPATH的任意路径（如：应用的classes目录）下新建一个threadpool4j.xml的配置文件，其内容为”
这里写明了在Classpath中进行配置，但是我的是普通的执行项目，没有这个目录，于是就按照你源码上的放在conf/biz下面，报错Exception in thread "main" java.lang.IllegalArgumentException: thread pool default not exists，然后放在工程目录下也是这样，放在src目录下还是这样，不知道怎么解决，请指教下

**Comment by rtwo1987** [comment]
@aofeng 请教~

**Comment by aofeng** [comment]
你项目中的*.class文件存放的根目录就属于项目的CLASSPATH，在该根目录下新建子目录conf/biz并把threadpool4j.xml放入即可。
