### ISSUE TITLE
单例问题

### ISSUE THREAD

**Issue by ixufeng** [aofeng/threadpool4j#6]
建议把 初始化线程池的工作放到ThreadPoolManager里，目前的设计，用户完全可以绕过ThreadPoolManager ,而初始化多个ThreadPool。

**Comment by aofeng** [comment]
做为一个公共组件，除了提供标准的操作，也不能堵死扩展的路径。
做为使用者，如果真的想要多个ThreadPool，说明有他的需要，聪明之人不会给自己埋坑的。
