### ISSUE TITLE
添加1万个任务后，一个一个执行过程中出错

### ISSUE THREAD

**Issue by Sabirjan** [aofeng/threadpool4j#7]
比如 先有1万个任务要多线程处理，互不影响。但是我调用后执行过程中出错：
name:threadpool4j-threadstack, id:16, status:RUNNABLE, priority:5
java.lang.Thread.dumpThreads(Native Method)
java.lang.Thread.getAllStackTraces(Thread.java:1610)
cn.aofeng.threadpool4j.job.ThreadStackJob.execute(ThreadStackJob.java:26)
cn.aofeng.threadpool4j.job.AbstractJob.run(AbstractJob.java:34)
java.lang.Thread.run(Thread.java:748)

**Comment by Sabirjan** [comment]
然后Runnable 怎么并行执行，我先看好像觉得串行执行

**Comment by Sabirjan** [comment]
tpm.getThreadPool().invokeAll(tasks, 3, TimeUnit.SECONDS);  这个超时时间，能不能去掉啊，这样限制太大了吧，每个任务的完成时间不一样，

**Comment by aofeng** [comment]
不同任务的执行时间不同，可以把它们放入不同的线程池执行，让执行快的任务尽快完成，避免慢的任务影响快的任务，就像高速公路划分快车道和慢车道一样。
